import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
// import ReduxToolkit from "@/utils/ReduxToolkit";
import { ReactQuery } from "@/utils/ReactQuery";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReactQuery>
          <Provider>{children}</Provider>
        </ReactQuery>
      </body>
    </html>
  );
}
